#pragma once

#define MS_ECG_SAMPLE_RATE_HZ 500U
#define MS_ECG_SPI_CLOCK_HZ 1000000U
#define MS_ECG_CHANNEL_COUNT 4U
#define MS_ECG_ACTIVE_LEADS 3U
#define MS_ECG_FRAME_BYTES (3U + (MS_ECG_CHANNEL_COUNT * 3U))
#define MS_ECG_QUEUE_DEPTH 1024U
#define MS_STORAGE_QUEUE_DEPTH 256U
#define MS_ECG_SATURATION_LIMIT 7600000
#define MS_BINARY_FORMAT_VERSION 1U
