#pragma once

#define BOARD_ECG_MOSI_GPIO 36
#define BOARD_ECG_PWDN_GPIO 35
#define BOARD_ECG_RESET_GPIO 34
#define BOARD_ECG_START_GPIO 33
#define BOARD_ECG_CS_GPIO 21
#define BOARD_ECG_SCLK_GPIO 18
#define BOARD_ECG_MISO_GPIO 17
#define BOARD_ECG_DRDY_GPIO 16

#define BOARD_SD_CS_GPIO 39
#define BOARD_SD_MOSI_GPIO 38
#define BOARD_SD_SCLK_GPIO 37
#define BOARD_SD_MISO_GPIO 13
